// Copyright 2026 Cloud Surfers GmbH
// SPDX-License-Identifier: Apache-2.0

// The swarmexec wire protocol: the single definition of its messages, fields
// and RPCs. What they mean — transport, authentication, framing, lifecycles —
// is CONTRACT.md, which does not repeat this file. Generated Go code lands in
// internal/pb (make generate) and is shared by the cli and the agent; CI fails
// when it does not match this file.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: swarmexec.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Agent_ListContainers_FullMethodName       = "/swarmexec.Agent/ListContainers"
	Agent_Exec_FullMethodName                 = "/swarmexec.Agent/Exec"
	Agent_Logs_FullMethodName                 = "/swarmexec.Agent/Logs"
	Agent_WatchContainerEvents_FullMethodName = "/swarmexec.Agent/WatchContainerEvents"
	Agent_ListVolumes_FullMethodName          = "/swarmexec.Agent/ListVolumes"
	Agent_RemoveVolume_FullMethodName         = "/swarmexec.Agent/RemoveVolume"
	Agent_CreateVolume_FullMethodName         = "/swarmexec.Agent/CreateVolume"
	Agent_PortForward_FullMethodName          = "/swarmexec.Agent/PortForward"
	Agent_Stats_FullMethodName                = "/swarmexec.Agent/Stats"
	Agent_ListImages_FullMethodName           = "/swarmexec.Agent/ListImages"
	Agent_PruneImages_FullMethodName          = "/swarmexec.Agent/PruneImages"
	Agent_Version_FullMethodName              = "/swarmexec.Agent/Version"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	// List containers on THIS node. Optional helper for discovery/validation.
	ListContainers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Bidirectional interactive exec stream.
	// The first ClientMessage on the stream MUST carry a StartExec payload.
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
	// Stream a container's logs. Server-streaming: the agent reads the container
	// logs on its own node and forwards them as LogChunks until the request is
	// satisfied (or, with follow=true, until the client cancels the stream).
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
	// Stream one container's runtime events from THIS node: health transitions,
	// OOM kills, exits with their code, starts and restarts. The manager carries
	// none of these — a task reads "running" while its container fails every
	// probe — so they can only come from the node.
	//
	// Deliberately ONE container, not the node's stream: the client opens this
	// over the connection it already holds for the view the operator has open, so
	// there is no fan-out, and nothing about the node's other containers (swarm
	// or not) crosses the wire.
	WatchContainerEvents(ctx context.Context, in *WatchContainerEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ContainerEvent], error)
	// List volumes on THIS node. Swarm volumes are node-local, so the cli queries
	// every node and aggregates the results.
	ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error)
	// Remove a volume on THIS node (authorized + audited). Fails if the volume is
	// in use unless force is set.
	RemoveVolume(ctx context.Context, in *RemoveVolumeRequest, opts ...grpc.CallOption) (*RemoveVolumeResponse, error)
	// Create a volume on THIS node (authorized + audited). Volumes are node-local,
	// so the cli targets a specific node's agent.
	CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error)
	// Forward a single TCP connection to a port inside a container on THIS node.
	// Bidirectional: one stream carries exactly one connection, so a local
	// listener opens a new stream per accepted conn (HTTP/2 multiplexes them over
	// the one transport). The first ClientMessage MUST carry a StartForward.
	PortForward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ForwardClientMessage, ForwardServerMessage], error)
	// Resource usage of the containers on THIS node. Unary on purpose: the agent
	// samples in the background and answers from memory, so a client polls this on
	// the refresh cycle it already has instead of holding a stream open per node.
	// It also solves the sampling problem — a CPU percentage needs two readings,
	// and the background sampler always has the previous one.
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// List the images on THIS node, with what each costs on disk and whether a
	// running container is using it. Images are node-local and the manager has no
	// view of them at all, so the cli asks each node in turn.
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	// Reclaim image disk space on THIS node (authorized + audited). Destructive:
	// see PruneImagesRequest.all for the two very different things it can mean.
	PruneImages(ctx context.Context, in *PruneImagesRequest, opts ...grpc.CallOption) (*PruneImagesResponse, error)
	// Report the agent's build and protocol version. Cheap, low-privilege probe
	// used by `swarmexec doctor` and for client/agent skew detection. Calling it
	// on an agent that predates this RPC yields gRPC Unimplemented, which the cli
	// turns into an "agent too old — run init --force" hint.
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) ListContainers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, Agent_ListContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[0], Agent_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_ExecClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

func (c *agentClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[1], Agent_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_LogsClient = grpc.ServerStreamingClient[LogChunk]

func (c *agentClient) WatchContainerEvents(ctx context.Context, in *WatchContainerEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ContainerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[2], Agent_WatchContainerEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchContainerEventsRequest, ContainerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_WatchContainerEventsClient = grpc.ServerStreamingClient[ContainerEvent]

func (c *agentClient) ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumesResponse)
	err := c.cc.Invoke(ctx, Agent_ListVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) RemoveVolume(ctx context.Context, in *RemoveVolumeRequest, opts ...grpc.CallOption) (*RemoveVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveVolumeResponse)
	err := c.cc.Invoke(ctx, Agent_RemoveVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVolumeResponse)
	err := c.cc.Invoke(ctx, Agent_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) PortForward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ForwardClientMessage, ForwardServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[3], Agent_PortForward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ForwardClientMessage, ForwardServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_PortForwardClient = grpc.BidiStreamingClient[ForwardClientMessage, ForwardServerMessage]

func (c *agentClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, Agent_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, Agent_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) PruneImages(ctx context.Context, in *PruneImagesRequest, opts ...grpc.CallOption) (*PruneImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PruneImagesResponse)
	err := c.cc.Invoke(ctx, Agent_PruneImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, Agent_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
type AgentServer interface {
	// List containers on THIS node. Optional helper for discovery/validation.
	ListContainers(context.Context, *ListRequest) (*ListResponse, error)
	// Bidirectional interactive exec stream.
	// The first ClientMessage on the stream MUST carry a StartExec payload.
	Exec(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	// Stream a container's logs. Server-streaming: the agent reads the container
	// logs on its own node and forwards them as LogChunks until the request is
	// satisfied (or, with follow=true, until the client cancels the stream).
	Logs(*LogsRequest, grpc.ServerStreamingServer[LogChunk]) error
	// Stream one container's runtime events from THIS node: health transitions,
	// OOM kills, exits with their code, starts and restarts. The manager carries
	// none of these — a task reads "running" while its container fails every
	// probe — so they can only come from the node.
	//
	// Deliberately ONE container, not the node's stream: the client opens this
	// over the connection it already holds for the view the operator has open, so
	// there is no fan-out, and nothing about the node's other containers (swarm
	// or not) crosses the wire.
	WatchContainerEvents(*WatchContainerEventsRequest, grpc.ServerStreamingServer[ContainerEvent]) error
	// List volumes on THIS node. Swarm volumes are node-local, so the cli queries
	// every node and aggregates the results.
	ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error)
	// Remove a volume on THIS node (authorized + audited). Fails if the volume is
	// in use unless force is set.
	RemoveVolume(context.Context, *RemoveVolumeRequest) (*RemoveVolumeResponse, error)
	// Create a volume on THIS node (authorized + audited). Volumes are node-local,
	// so the cli targets a specific node's agent.
	CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error)
	// Forward a single TCP connection to a port inside a container on THIS node.
	// Bidirectional: one stream carries exactly one connection, so a local
	// listener opens a new stream per accepted conn (HTTP/2 multiplexes them over
	// the one transport). The first ClientMessage MUST carry a StartForward.
	PortForward(grpc.BidiStreamingServer[ForwardClientMessage, ForwardServerMessage]) error
	// Resource usage of the containers on THIS node. Unary on purpose: the agent
	// samples in the background and answers from memory, so a client polls this on
	// the refresh cycle it already has instead of holding a stream open per node.
	// It also solves the sampling problem — a CPU percentage needs two readings,
	// and the background sampler always has the previous one.
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	// List the images on THIS node, with what each costs on disk and whether a
	// running container is using it. Images are node-local and the manager has no
	// view of them at all, so the cli asks each node in turn.
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	// Reclaim image disk space on THIS node (authorized + audited). Destructive:
	// see PruneImagesRequest.all for the two very different things it can mean.
	PruneImages(context.Context, *PruneImagesRequest) (*PruneImagesResponse, error)
	// Report the agent's build and protocol version. Cheap, low-privilege probe
	// used by `swarmexec doctor` and for client/agent skew detection. Calling it
	// on an agent that predates this RPC yields gRPC Unimplemented, which the cli
	// turns into an "agent too old — run init --force" hint.
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) ListContainers(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContainers not implemented")
}
func (UnimplementedAgentServer) Exec(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedAgentServer) Logs(*LogsRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Errorf(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedAgentServer) WatchContainerEvents(*WatchContainerEventsRequest, grpc.ServerStreamingServer[ContainerEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchContainerEvents not implemented")
}
func (UnimplementedAgentServer) ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedAgentServer) RemoveVolume(context.Context, *RemoveVolumeRequest) (*RemoveVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveVolume not implemented")
}
func (UnimplementedAgentServer) CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedAgentServer) PortForward(grpc.BidiStreamingServer[ForwardClientMessage, ForwardServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method PortForward not implemented")
}
func (UnimplementedAgentServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedAgentServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedAgentServer) PruneImages(context.Context, *PruneImagesRequest) (*PruneImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PruneImages not implemented")
}
func (UnimplementedAgentServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call pancis, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_ListContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListContainers(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServer).Exec(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_ExecServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

func _Agent_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).Logs(m, &grpc.GenericServerStream[LogsRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_LogsServer = grpc.ServerStreamingServer[LogChunk]

func _Agent_WatchContainerEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchContainerEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).WatchContainerEvents(m, &grpc.GenericServerStream[WatchContainerEventsRequest, ContainerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_WatchContainerEventsServer = grpc.ServerStreamingServer[ContainerEvent]

func _Agent_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListVolumes(ctx, req.(*ListVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_RemoveVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).RemoveVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_RemoveVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).RemoveVolume(ctx, req.(*RemoveVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CreateVolume(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_PortForward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServer).PortForward(&grpc.GenericServerStream[ForwardClientMessage, ForwardServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_PortForwardServer = grpc.BidiStreamingServer[ForwardClientMessage, ForwardServerMessage]

func _Agent_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_PruneImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PruneImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PruneImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_PruneImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PruneImages(ctx, req.(*PruneImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swarmexec.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListContainers",
			Handler:    _Agent_ListContainers_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _Agent_ListVolumes_Handler,
		},
		{
			MethodName: "RemoveVolume",
			Handler:    _Agent_RemoveVolume_Handler,
		},
		{
			MethodName: "CreateVolume",
			Handler:    _Agent_CreateVolume_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Agent_Stats_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _Agent_ListImages_Handler,
		},
		{
			MethodName: "PruneImages",
			Handler:    _Agent_PruneImages_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _Agent_Version_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _Agent_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Logs",
			Handler:       _Agent_Logs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchContainerEvents",
			Handler:       _Agent_WatchContainerEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PortForward",
			Handler:       _Agent_PortForward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "swarmexec.proto",
}
