// Authoritative wire protocol for swarmexec. Source of truth: CONTRACT.md §3.
// Generated Go code lands in internal/pb and is shared by the cli and agent.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: swarmexec.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceFilter string `protobuf:"bytes,1,opt,name=service_filter,json=serviceFilter,proto3" json:"service_filter,omitempty"` // optional substring/label filter; empty = all
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swarmexec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarmexec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_swarmexec_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetServiceFilter() string {
	if x != nil {
		return x.ServiceFilter
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Containers []*ContainerInfo `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swarmexec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarmexec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_swarmexec_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ContainerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // full container ID
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       // container name
	Service string `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"` // swarm service name if known, else empty
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swarmexec_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_swarmexec_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_swarmexec_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerInfo) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ClientMessage_Start
	//	*ClientMessage_Stdin
	//	*ClientMessage_Resize
	Payload isClientMessage_Payload `protobuf_oneof:"payload"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swarmexec_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_swarmexec_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_swarmexec_proto_rawDescGZIP(), []int{3}
}

func (m *ClientMessage) GetPayload() isClientMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ClientMessage) GetStart() *StartExec {
	if x, ok := x.GetPayload().(*ClientMessage_Start); ok {
		return x.Start
	}
	return nil
}

func (x *ClientMessage) GetStdin() []byte {
	if x, ok := x.GetPayload().(*ClientMessage_Stdin); ok {
		return x.Stdin
	}
	return nil
}

func (x *ClientMessage) GetResize() *Resize {
	if x, ok := x.GetPayload().(*ClientMessage_Resize); ok {
		return x.Resize
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Start struct {
	Start *StartExec `protobuf:"bytes,1,opt,name=start,proto3,oneof"` // MUST be the first message
}

type ClientMessage_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"` // raw stdin bytes
}

type ClientMessage_Resize struct {
	Resize *Resize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"` // terminal resize event
}

func (*ClientMessage_Start) isClientMessage_Payload() {}

func (*ClientMessage_Stdin) isClientMessage_Payload() {}

func (*ClientMessage_Resize) isClientMessage_Payload() {}

type StartExec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerId string   `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"` // full container ID to exec into
	Cmd         []string `protobuf:"bytes,2,rep,name=cmd,proto3" json:"cmd,omitempty"`                                    // command + args, e.g. ["/bin/sh"]
	Tty         bool     `protobuf:"varint,3,opt,name=tty,proto3" json:"tty,omitempty"`                                   // allocate a TTY
	Width       uint32   `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`                               // initial terminal width (columns)
	Height      uint32   `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`                             // initial terminal height (rows)
	Env         []string `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty"`                                    // optional extra env, "KEY=VALUE"
	WorkingDir  string   `protobuf:"bytes,7,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`    // optional working directory
	User        string   `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`                                  // optional user, e.g. "1000:1000" or "root"
}

func (x *StartExec) Reset() {
	*x = StartExec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swarmexec_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartExec) ProtoMessage() {}

func (x *StartExec) ProtoReflect() protoreflect.Message {
	mi := &file_swarmexec_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartExec.ProtoReflect.Descriptor instead.
func (*StartExec) Descriptor() ([]byte, []int) {
	return file_swarmexec_proto_rawDescGZIP(), []int{4}
}

func (x *StartExec) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StartExec) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *StartExec) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *StartExec) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *StartExec) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *StartExec) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StartExec) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *StartExec) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type Resize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  uint32 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *Resize) Reset() {
	*x = Resize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swarmexec_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_swarmexec_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_swarmexec_proto_rawDescGZIP(), []int{5}
}

func (x *Resize) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Resize) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ServerMessage_Stdout
	//	*ServerMessage_Stderr
	//	*ServerMessage_ExitCode
	//	*ServerMessage_Error
	Payload isServerMessage_Payload `protobuf_oneof:"payload"`
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swarmexec_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_swarmexec_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_swarmexec_proto_rawDescGZIP(), []int{6}
}

func (m *ServerMessage) GetPayload() isServerMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ServerMessage) GetStdout() []byte {
	if x, ok := x.GetPayload().(*ServerMessage_Stdout); ok {
		return x.Stdout
	}
	return nil
}

func (x *ServerMessage) GetStderr() []byte {
	if x, ok := x.GetPayload().(*ServerMessage_Stderr); ok {
		return x.Stderr
	}
	return nil
}

func (x *ServerMessage) GetExitCode() int32 {
	if x, ok := x.GetPayload().(*ServerMessage_ExitCode); ok {
		return x.ExitCode
	}
	return 0
}

func (x *ServerMessage) GetError() string {
	if x, ok := x.GetPayload().(*ServerMessage_Error); ok {
		return x.Error
	}
	return ""
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"` // stdout bytes (also carries all output when tty=true)
}

type ServerMessage_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"` // stderr bytes (only when tty=false)
}

type ServerMessage_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"` // sent once, as the final message before stream end
}

type ServerMessage_Error struct {
	Error string `protobuf:"bytes,4,opt,name=error,proto3,oneof"` // terminal error; stream ends after this
}

func (*ServerMessage_Stdout) isServerMessage_Payload() {}

func (*ServerMessage_Stderr) isServerMessage_Payload() {}

func (*ServerMessage_ExitCode) isServerMessage_Payload() {}

func (*ServerMessage_Error) isServerMessage_Payload() {}

type LogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerId  string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`     // full container ID to read logs from
	Follow       bool   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`                                 // keep streaming new log lines as they arrive
	Tail         uint32 `protobuf:"varint,3,opt,name=tail,proto3" json:"tail,omitempty"`                                     // last N lines to start from; 0 = all
	Timestamps   bool   `protobuf:"varint,4,opt,name=timestamps,proto3" json:"timestamps,omitempty"`                         // prefix each line with an RFC3339Nano timestamp
	SinceSeconds uint32 `protobuf:"varint,5,opt,name=since_seconds,json=sinceSeconds,proto3" json:"since_seconds,omitempty"` // only logs newer than N seconds ago; 0 = no limit
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swarmexec_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarmexec_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_swarmexec_proto_rawDescGZIP(), []int{7}
}

func (x *LogsRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetTail() uint32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

func (x *LogsRequest) GetTimestamps() bool {
	if x != nil {
		return x.Timestamps
	}
	return false
}

func (x *LogsRequest) GetSinceSeconds() uint32 {
	if x != nil {
		return x.SinceSeconds
	}
	return 0
}

type LogChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*LogChunk_Stdout
	//	*LogChunk_Stderr
	//	*LogChunk_Error
	Payload isLogChunk_Payload `protobuf_oneof:"payload"`
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swarmexec_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_swarmexec_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_swarmexec_proto_rawDescGZIP(), []int{8}
}

func (m *LogChunk) GetPayload() isLogChunk_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *LogChunk) GetStdout() []byte {
	if x, ok := x.GetPayload().(*LogChunk_Stdout); ok {
		return x.Stdout
	}
	return nil
}

func (x *LogChunk) GetStderr() []byte {
	if x, ok := x.GetPayload().(*LogChunk_Stderr); ok {
		return x.Stderr
	}
	return nil
}

func (x *LogChunk) GetError() string {
	if x, ok := x.GetPayload().(*LogChunk_Error); ok {
		return x.Error
	}
	return ""
}

type isLogChunk_Payload interface {
	isLogChunk_Payload()
}

type LogChunk_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"` // stdout bytes (also carries all output for TTY containers)
}

type LogChunk_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"` // stderr bytes (non-TTY containers only)
}

type LogChunk_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"` // terminal error; stream ends after this
}

func (*LogChunk_Stdout) isLogChunk_Payload() {}

func (*LogChunk_Stderr) isLogChunk_Payload() {}

func (*LogChunk_Error) isLogChunk_Payload() {}

var File_swarmexec_proto protoreflect.FileDescriptor

var file_swarmexec_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x77, 0x61, 0x72, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x73, 0x77, 0x61, 0x72, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x22, 0x34, 0x0a, 0x0b,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x22, 0x48, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x77, 0x61, 0x72, 0x6d, 0x65, 0x78,
	0x65, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x4d, 0x0a, 0x0d,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x0d,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73,
	0x77, 0x61, 0x72, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x78,
	0x65, 0x63, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x05, 0x73,
	0x74, 0x64, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74,
	0x64, 0x69, 0x6e, 0x12, 0x2b, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x77, 0x61, 0x72, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2e,
	0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65,
	0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xc7, 0x01, 0x0a, 0x09,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x78, 0x65, 0x63, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x74, 0x74, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x76,
	0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x69, 0x72, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x69,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x85, 0x01,
	0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x18, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x00, 0x52, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x64,
	0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x64,
	0x65, 0x72, 0x72, 0x12, 0x1d, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xa1, 0x01, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x73, 0x69, 0x6e,
	0x63, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x61, 0x0a, 0x08, 0x4c, 0x6f, 0x67,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12,
	0x18, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x00, 0x52, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0xc1, 0x01, 0x0a,
	0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x41, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x73, 0x77, 0x61, 0x72, 0x6d,
	0x65, 0x78, 0x65, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x73, 0x77, 0x61, 0x72, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x04, 0x45, 0x78, 0x65,
	0x63, 0x12, 0x18, 0x2e, 0x73, 0x77, 0x61, 0x72, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x18, 0x2e, 0x73, 0x77,
	0x61, 0x72, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x35, 0x0a, 0x04, 0x4c, 0x6f, 0x67,
	0x73, 0x12, 0x16, 0x2e, 0x73, 0x77, 0x61, 0x72, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x4c, 0x6f,
	0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x77, 0x61, 0x72,
	0x6d, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x4c, 0x6f, 0x67, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x30, 0x01,
	0x42, 0x7a, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x77, 0x61, 0x72, 0x6d, 0x65, 0x78, 0x65,
	0x63, 0x42, 0x0e, 0x53, 0x77, 0x61, 0x72, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x15, 0x73, 0x77, 0x61, 0x72, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0xa2, 0x02, 0x03, 0x53, 0x58, 0x58,
	0xaa, 0x02, 0x09, 0x53, 0x77, 0x61, 0x72, 0x6d, 0x65, 0x78, 0x65, 0x63, 0xca, 0x02, 0x09, 0x53,
	0x77, 0x61, 0x72, 0x6d, 0x65, 0x78, 0x65, 0x63, 0xe2, 0x02, 0x15, 0x53, 0x77, 0x61, 0x72, 0x6d,
	0x65, 0x78, 0x65, 0x63, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x09, 0x53, 0x77, 0x61, 0x72, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_swarmexec_proto_rawDescOnce sync.Once
	file_swarmexec_proto_rawDescData = file_swarmexec_proto_rawDesc
)

func file_swarmexec_proto_rawDescGZIP() []byte {
	file_swarmexec_proto_rawDescOnce.Do(func() {
		file_swarmexec_proto_rawDescData = protoimpl.X.CompressGZIP(file_swarmexec_proto_rawDescData)
	})
	return file_swarmexec_proto_rawDescData
}

var file_swarmexec_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_swarmexec_proto_goTypes = []any{
	(*ListRequest)(nil),   // 0: swarmexec.ListRequest
	(*ListResponse)(nil),  // 1: swarmexec.ListResponse
	(*ContainerInfo)(nil), // 2: swarmexec.ContainerInfo
	(*ClientMessage)(nil), // 3: swarmexec.ClientMessage
	(*StartExec)(nil),     // 4: swarmexec.StartExec
	(*Resize)(nil),        // 5: swarmexec.Resize
	(*ServerMessage)(nil), // 6: swarmexec.ServerMessage
	(*LogsRequest)(nil),   // 7: swarmexec.LogsRequest
	(*LogChunk)(nil),      // 8: swarmexec.LogChunk
}
var file_swarmexec_proto_depIdxs = []int32{
	2, // 0: swarmexec.ListResponse.containers:type_name -> swarmexec.ContainerInfo
	4, // 1: swarmexec.ClientMessage.start:type_name -> swarmexec.StartExec
	5, // 2: swarmexec.ClientMessage.resize:type_name -> swarmexec.Resize
	0, // 3: swarmexec.Agent.ListContainers:input_type -> swarmexec.ListRequest
	3, // 4: swarmexec.Agent.Exec:input_type -> swarmexec.ClientMessage
	7, // 5: swarmexec.Agent.Logs:input_type -> swarmexec.LogsRequest
	1, // 6: swarmexec.Agent.ListContainers:output_type -> swarmexec.ListResponse
	6, // 7: swarmexec.Agent.Exec:output_type -> swarmexec.ServerMessage
	8, // 8: swarmexec.Agent.Logs:output_type -> swarmexec.LogChunk
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_swarmexec_proto_init() }
func file_swarmexec_proto_init() {
	if File_swarmexec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_swarmexec_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swarmexec_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swarmexec_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ContainerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swarmexec_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swarmexec_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*StartExec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swarmexec_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Resize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swarmexec_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swarmexec_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*LogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swarmexec_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*LogChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_swarmexec_proto_msgTypes[3].OneofWrappers = []any{
		(*ClientMessage_Start)(nil),
		(*ClientMessage_Stdin)(nil),
		(*ClientMessage_Resize)(nil),
	}
	file_swarmexec_proto_msgTypes[6].OneofWrappers = []any{
		(*ServerMessage_Stdout)(nil),
		(*ServerMessage_Stderr)(nil),
		(*ServerMessage_ExitCode)(nil),
		(*ServerMessage_Error)(nil),
	}
	file_swarmexec_proto_msgTypes[8].OneofWrappers = []any{
		(*LogChunk_Stdout)(nil),
		(*LogChunk_Stderr)(nil),
		(*LogChunk_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_swarmexec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swarmexec_proto_goTypes,
		DependencyIndexes: file_swarmexec_proto_depIdxs,
		MessageInfos:      file_swarmexec_proto_msgTypes,
	}.Build()
	File_swarmexec_proto = out.File
	file_swarmexec_proto_rawDesc = nil
	file_swarmexec_proto_goTypes = nil
	file_swarmexec_proto_depIdxs = nil
}
