#!/bin/sh
# Generate a Homebrew formula and a Scoop manifest for one release, from the
# release's own SHA256SUMS — so the hashes in them are exactly the ones the
# release published, never recomputed from a second build.
#
#   ci/package-manifests.sh <tag> <base-url> <SHA256SUMS> <out-dir>
#
# <base-url> is the directory holding the release's binaries, e.g.
# https://gitlab.logle.io/api/v4/projects/242/packages/generic/swarmexec/v1.19.2
#
# It only WRITES the two files; ci/publish-packages.sh pushes them to the tap
# and the bucket (the publish-packages CI job), when those are configured.
set -eu

tag=$1
base=${2%/}
sums=$3
out=$4
version=${tag#v}

sum() {
	h=$(awk -v n="$1" '$2 == n || $2 == "*"n { print $1 }' "$sums")
	[ -n "$h" ] || { echo "package-manifests: $1 is not in $sums" >&2; exit 1; }
	printf '%s' "$h"
}

mkdir -p "$out"

cat >"$out/swarmexec.rb" <<RUBY
# Homebrew formula for swarmexec $version — generated by ci/package-manifests.sh.
class Swarmexec < Formula
  desc "Exec, logs and port-forward into any container of a Docker Swarm, without SSH"
  homepage "https://swarm-exec.cloud-surfers.net"
  version "$version"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$base/swarmexec-darwin-arm64"
      sha256 "$(sum swarmexec-darwin-arm64)"
    end
    on_intel do
      url "$base/swarmexec-darwin-amd64"
      sha256 "$(sum swarmexec-darwin-amd64)"
    end
  end

  on_linux do
    on_arm do
      url "$base/swarmexec-linux-arm64"
      sha256 "$(sum swarmexec-linux-arm64)"
    end
    on_intel do
      url "$base/swarmexec-linux-amd64"
      sha256 "$(sum swarmexec-linux-amd64)"
    end
  end

  def install
    # The release ships bare binaries, not archives: install whichever one was
    # downloaded for this platform under its real name.
    bin.install Dir["swarmexec-*"].first => "swarmexec"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/swarmexec --version")
  end
end
RUBY

cat >"$out/swarmexec.json" <<JSON
{
  "version": "$version",
  "description": "Exec, logs and port-forward into any container of a Docker Swarm, without SSH",
  "homepage": "https://swarm-exec.cloud-surfers.net",
  "license": "Apache-2.0",
  "architecture": {
    "64bit": {
      "url": "$base/swarmexec-windows-amd64.exe#/swarmexec.exe",
      "hash": "$(sum swarmexec-windows-amd64.exe)"
    }
  },
  "bin": "swarmexec.exe"
}
JSON

echo "wrote $out/swarmexec.rb and $out/swarmexec.json for $tag"
